on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gpregistry12.azurecr.io
        username: ${{ secrets.acr_gpregistry12_username }}
        password: ${{ secrets.acr_gpregistry12_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t gpregistry12.azurecr.io/aks1:${{ github.sha }}
        docker push gpregistry12.azurecr.io/aks1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks10137 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks10137`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks10137
        container-registry-url: gpregistry12.azurecr.io
        container-registry-username: ${{ secrets.acr_gpregistry12_username }}
        container-registry-password: ${{ secrets.acr_gpregistry12_password }}
        secret-name: aks1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aks10137
        manifests: |
          manifests/deployment-1.yml
          manifests/service.yml
          manifests/ingress-1.yml
        images: |
          gpregistry12.azurecr.io/aks1:${{ github.sha }}
        imagepullsecrets: |
          aks1dockerauth